env:
  global:
  - GIT_NAME: "'Automatic Publish'"
  - GIT_EMAIL: ganeticon@googlegroups.com
  - GH_REF: git@github.com:ganeticon/ganeticon.github.io.git
language: python
python:
- '3.5'
before_install:
- openssl aes-256-cbc -K $encrypted_d327c61dbe40_key -iv $encrypted_d327c61dbe40_iv
  -in deploy-key.enc -out deploy-key -d
install: pip3 install -q -r requirements.txt
script:
- chmod 600 deploy-key
- eval `ssh-agent -s`
- ssh-add deploy-key
- git config user.name "${GIT_NAME}"
- git config user.email "${GIT_EMAIL}"
- git remote add gh-token "${GH_REF}";
- git fetch gh-token && git fetch gh-token master:master;
- if [ "${TRAVIS_PULL_REQUEST}" = "false" ]; then echo "Pushing to github"; PYTHONPATH=src/
  mkdocs gh-deploy -v --clean --remote-branch master --remote-name gh-token; 
  git push gh-token master;
  fi;
